\
# Template de server.properties — Pangeia
# Ajuste server-ip/motd conforme exigido pelo painel do host gerenciado.

motd=Pangeia
difficulty=hard
hardcore=false
pvp=true
online-mode=true
spawn-protection=0
allow-nether=true
allow-end=true
level-name=world
level-type=minecraft\:normal
view-distance=10
simulation-distance=8
max-players=100
white-list=false
enforce-whitelist=false
gamemode=survival
force-gamemode=false
enable-command-block=false
spawn-monsters=true
spawn-animals=true
spawn-npcs=true
generate-structures=true
